{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "security",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "security-2.0.0.aar",
          "url": "security-2.0.0.aar",
          "size": 145610,
          "sha512": "5ad5772cde5a94c0627bbdbb92c1be26abb4b77c10ac8fbe8f64c8ec58ca8f9278f2f94120272df8d04ba0e1fc3d1ea5ad633dc79bdb68e5926ed79d048fc584",
          "sha256": "37337bb20ddeba082f0deedc69941ea79de4dce74f7eae082eca96fce41c2ff7",
          "sha1": "022417d89c03f009140e6af6bb3cff7d70e24aa8",
          "md5": "381ae1d7d48c2f13eefce35829bc7f76"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "security-2.0.0.aar",
          "url": "security-2.0.0.aar",
          "size": 145610,
          "sha512": "5ad5772cde5a94c0627bbdbb92c1be26abb4b77c10ac8fbe8f64c8ec58ca8f9278f2f94120272df8d04ba0e1fc3d1ea5ad633dc79bdb68e5926ed79d048fc584",
          "sha256": "37337bb20ddeba082f0deedc69941ea79de4dce74f7eae082eca96fce41c2ff7",
          "sha1": "022417d89c03f009140e6af6bb3cff7d70e24aa8",
          "md5": "381ae1d7d48c2f13eefce35829bc7f76"
        }
      ]
    }
  ]
}
