{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness3d-sdk",
    "version": "6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "liveness3d-sdk-6.3.aar",
          "url": "liveness3d-sdk-6.3.aar",
          "size": 2199853,
          "sha512": "240870e8560d9598cf7b06db87699c6a95c89bc280100f16cf1fdc9f4d317b221d5e43a2c629e05da1856d2e5b1c146a6aa90df714fae21eb110ce9b6765d707",
          "sha256": "9c1385e8731ec255cebc908917dde8873ffdeb215c5237e7a551f863601cbe67",
          "sha1": "054bb07d052130d1ac664324a9005ca0afa2659b",
          "md5": "46e7841d8d1757b5709f4a06624ce601"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.6.15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "liveness3d-sdk-6.3.aar",
          "url": "liveness3d-sdk-6.3.aar",
          "size": 2199853,
          "sha512": "240870e8560d9598cf7b06db87699c6a95c89bc280100f16cf1fdc9f4d317b221d5e43a2c629e05da1856d2e5b1c146a6aa90df714fae21eb110ce9b6765d707",
          "sha256": "9c1385e8731ec255cebc908917dde8873ffdeb215c5237e7a551f863601cbe67",
          "sha1": "054bb07d052130d1ac664324a9005ca0afa2659b",
          "md5": "46e7841d8d1757b5709f4a06624ce601"
        }
      ]
    }
  ]
}
