{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "security",
    "version": "3.1.4-pre-migration",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "security-3.1.4-pre-migration.aar",
          "url": "security-3.1.4-pre-migration.aar",
          "size": 104566,
          "sha512": "1baa7944f227828829a2940a28146efb52dbe0318d841ead3c03c3744d60631dd6df3e561e4d9519ded56174b6a095591528688cf75bfdbcb690f362acda74c2",
          "sha256": "393b8435bdc981a6b328eb9892fa66bcf5cfed07a90a3f2445683b8b56f5a3f8",
          "sha1": "e7ac5d9842a413c73c673c6fe0396ad01dc69c01",
          "md5": "d7ecfd1fd22b54317699563ee0dd5ca1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "2.1.1-pre-migration"
          }
        }
      ],
      "files": [
        {
          "name": "security-3.1.4-pre-migration.aar",
          "url": "security-3.1.4-pre-migration.aar",
          "size": 104566,
          "sha512": "1baa7944f227828829a2940a28146efb52dbe0318d841ead3c03c3744d60631dd6df3e561e4d9519ded56174b6a095591528688cf75bfdbcb690f362acda74c2",
          "sha256": "393b8435bdc981a6b328eb9892fa66bcf5cfed07a90a3f2445683b8b56f5a3f8",
          "sha1": "e7ac5d9842a413c73c673c6fe0396ad01dc69c01",
          "md5": "d7ecfd1fd22b54317699563ee0dd5ca1"
        }
      ]
    }
  ]
}
