{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.6.1.aar",
          "url": "liveness2d-sdk-5.6.1.aar",
          "size": 2544268,
          "sha512": "a9c81e56e10c927abfae2a98bcec0c08b76ceba47266986b16513f52549ec19029ef435bb5ce06b02c054ac2965f46433448233c71f249fda8eec4d5f28dd5b4",
          "sha256": "233e0a9962806041e5beb9b73955929598fb5784662f7adfed0a27e435134e77",
          "sha1": "dde496d712b47ebdaefdfc16202b90a094bfb4e2",
          "md5": "ab6e4ce1f9ced4c3115e4da8893aca5f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.6.1.aar",
          "url": "liveness2d-sdk-5.6.1.aar",
          "size": 2544268,
          "sha512": "a9c81e56e10c927abfae2a98bcec0c08b76ceba47266986b16513f52549ec19029ef435bb5ce06b02c054ac2965f46433448233c71f249fda8eec4d5f28dd5b4",
          "sha256": "233e0a9962806041e5beb9b73955929598fb5784662f7adfed0a27e435134e77",
          "sha1": "dde496d712b47ebdaefdfc16202b90a094bfb4e2",
          "md5": "ab6e4ce1f9ced4c3115e4da8893aca5f"
        }
      ]
    }
  ]
}
