{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "security",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.1.aar",
          "url": "security-1.1.aar",
          "size": 72034,
          "sha512": "f31cc75d53c9bf25bd5fbf795cd4ea3b7d7c4476a5bca163b3faeda7b69def7a044cab62aa5cc8cfda0a674df1687f551be7323f175d981e2074b25b9b67fbc1",
          "sha256": "0e05a7f142ac6105e1e733b908b3919c0fe36ced16aac348d63dad87886863d6",
          "sha1": "6c332a7813958084ef07677c2c5b10d01f872517",
          "md5": "cdc084baef3784adc91c8260432f4d95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx",
          "version": {
            "requires": "17.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.1.aar",
          "url": "security-1.1.aar",
          "size": 72034,
          "sha512": "f31cc75d53c9bf25bd5fbf795cd4ea3b7d7c4476a5bca163b3faeda7b69def7a044cab62aa5cc8cfda0a674df1687f551be7323f175d981e2074b25b9b67fbc1",
          "sha256": "0e05a7f142ac6105e1e733b908b3919c0fe36ced16aac348d63dad87886863d6",
          "sha1": "6c332a7813958084ef07677c2c5b10d01f872517",
          "md5": "cdc084baef3784adc91c8260432f4d95"
        }
      ]
    }
  ]
}
