{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "6.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-6.1.6.aar",
          "url": "liveness2d-sdk-6.1.6.aar",
          "size": 2698093,
          "sha512": "58ff6d41e06ec4148962d1ac1872a5c50832fd7d7e6faa35152039dcc55a43e36f059c665ccfc378e3247277f85f6b1cd04cf8a8db7a3dd782e6b7a0dd0dc339",
          "sha256": "3773a210c6f3d3d83c0d1f92e308a8ae3cb12b43b27fa7c34862774ad81fe3c5",
          "sha1": "ca500a7259d774cad0fc60bb180a19e887db91e9",
          "md5": "64ae175153c228826a92cdccc2e4540e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "security",
          "version": {
            "requires": "3.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-6.1.6.aar",
          "url": "liveness2d-sdk-6.1.6.aar",
          "size": 2698093,
          "sha512": "58ff6d41e06ec4148962d1ac1872a5c50832fd7d7e6faa35152039dcc55a43e36f059c665ccfc378e3247277f85f6b1cd04cf8a8db7a3dd782e6b7a0dd0dc339",
          "sha256": "3773a210c6f3d3d83c0d1f92e308a8ae3cb12b43b27fa7c34862774ad81fe3c5",
          "sha1": "ca500a7259d774cad0fc60bb180a19e887db91e9",
          "md5": "64ae175153c228826a92cdccc2e4540e"
        }
      ]
    }
  ]
}
