{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "security",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "security-3.0.1.aar",
          "url": "security-3.0.1.aar",
          "size": 145127,
          "sha512": "a4868ca32ebc1b238896a11cbe6975ee125b6719ceb114080833a4dbc1ac64b0fb1d224835bff1c1a8c8613a4e52302c9ced2779c40d394d0b059ab51a63a6f7",
          "sha256": "c39c708b3ceaf3d9927ba4ebe683b8eef2b8a6bb48f914d65445fc30038a4b5a",
          "sha1": "7e36b9c9747f4692ce299cb44b7fa8c8a3a95706",
          "md5": "706d5cfcf4342f8340cad6205370cffe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "security-3.0.1.aar",
          "url": "security-3.0.1.aar",
          "size": 145127,
          "sha512": "a4868ca32ebc1b238896a11cbe6975ee125b6719ceb114080833a4dbc1ac64b0fb1d224835bff1c1a8c8613a4e52302c9ced2779c40d394d0b059ab51a63a6f7",
          "sha256": "c39c708b3ceaf3d9927ba4ebe683b8eef2b8a6bb48f914d65445fc30038a4b5a",
          "sha1": "7e36b9c9747f4692ce299cb44b7fa8c8a3a95706",
          "md5": "706d5cfcf4342f8340cad6205370cffe"
        }
      ]
    }
  ]
}
