{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness3d-sdk",
    "version": "9.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "prdReleaseVariantPrdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "liveness3d-sdk-9.2.5.aar",
          "url": "liveness3d-sdk-9.2.5.aar",
          "size": 2350410,
          "sha512": "f79b221b2cb1cc28345ffd4a413cf7a1e9b5eeb2fca62ae68c11a96396e6f45498802ecd1cbbe4a2784f7cc23723151b79311b4913b2fe97e5e52533b61bb274",
          "sha256": "978e4f244a87c1c51865d0748fe5b6da4035414cbdc9503c24bc604b7a8d4626",
          "sha1": "705cdc470a8e973b6bcce0a5a4e0a41b838c145d",
          "md5": "8376f1dd8b4db7457e018f5643d7b3ce"
        }
      ]
    },
    {
      "name": "prdReleaseVariantPrdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.6.71"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "br.com.oiti",
          "module": "security",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "liveness3d-sdk-9.2.5.aar",
          "url": "liveness3d-sdk-9.2.5.aar",
          "size": 2350410,
          "sha512": "f79b221b2cb1cc28345ffd4a413cf7a1e9b5eeb2fca62ae68c11a96396e6f45498802ecd1cbbe4a2784f7cc23723151b79311b4913b2fe97e5e52533b61bb274",
          "sha256": "978e4f244a87c1c51865d0748fe5b6da4035414cbdc9503c24bc604b7a8d4626",
          "sha1": "705cdc470a8e973b6bcce0a5a4e0a41b838c145d",
          "md5": "8376f1dd8b4db7457e018f5643d7b3ce"
        }
      ]
    }
  ]
}
