{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 478258,
          "sha512": "d018cc4e21cc7b0917b0a4c6a275c4aca2a10faed551af0cfd9abda4ecb467dd413a802e2dd0798b1539f2ff55513d568b658051ddf2c9888039722e68c29cbf",
          "sha256": "e8e6ca37f915535b672c4a2445a08eec25945cce6d3abe0b162c0cbcd66f692d",
          "sha1": "7c1dcf06c15b85657b7c8c8a375a1d1f4ecc31fc",
          "md5": "4405a71cd996b1897d4674a6825c2e14"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "designSystem",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "facetec",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "docCore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "remote",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "local",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "deviceIntelligence",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "commons",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "liveness2d",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 478258,
          "sha512": "d018cc4e21cc7b0917b0a4c6a275c4aca2a10faed551af0cfd9abda4ecb467dd413a802e2dd0798b1539f2ff55513d568b658051ddf2c9888039722e68c29cbf",
          "sha256": "e8e6ca37f915535b672c4a2445a08eec25945cce6d3abe0b162c0cbcd66f692d",
          "sha1": "7c1dcf06c15b85657b7c8c8a375a1d1f4ecc31fc",
          "md5": "4405a71cd996b1897d4674a6825c2e14"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-1.0.0-sources.jar",
          "url": "core-1.0.0-sources.jar",
          "size": 141856,
          "sha512": "4c55797147e2d20f76874ee26ea4aa3c144d3b940c3021a74a33e21a650ae4c72e22f65607b244de056aea54db27a07da7f0e6935db5330007a44886d3d865f0",
          "sha256": "2c1731b3332665a02832cfcba73bc6a4f4738756feef9680d1eb86bdda08ad42",
          "sha1": "a096060d5807ab0f6ba10cadac92ee65cf807ced",
          "md5": "98a5d1f41c72ceeac12ad777c619b93d"
        }
      ]
    }
  ]
}
