{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness3d-sdk",
    "version": "9.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "prdReleaseVariantPrdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "liveness3d-sdk-9.5.4.aar",
          "url": "liveness3d-sdk-9.5.4.aar",
          "size": 2484187,
          "sha512": "1874b6b11cd61ba77e1af490fbda5a2288ddfbcc5f4449a135b3d42d68afe94e629483e55c82a5c3a323b2506c1825e0da7ca93a027b316cf39b7df9a2c9093e",
          "sha256": "ff4448b76d07d991050f7defed2ec2a170bc775402883a400a42dea8bdd02314",
          "sha1": "d4605960276cfda9b8e5e0e3b36bc1bc9131b260",
          "md5": "bd58dadd37de3432a81913a7ca8f7f52"
        }
      ]
    },
    {
      "name": "prdReleaseVariantPrdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.109"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.9"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.81"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "br.com.oiti",
          "module": "security",
          "version": {
            "requires": "3.1.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "liveness3d-sdk-9.5.4.aar",
          "url": "liveness3d-sdk-9.5.4.aar",
          "size": 2484187,
          "sha512": "1874b6b11cd61ba77e1af490fbda5a2288ddfbcc5f4449a135b3d42d68afe94e629483e55c82a5c3a323b2506c1825e0da7ca93a027b316cf39b7df9a2c9093e",
          "sha256": "ff4448b76d07d991050f7defed2ec2a170bc775402883a400a42dea8bdd02314",
          "sha1": "d4605960276cfda9b8e5e0e3b36bc1bc9131b260",
          "md5": "bd58dadd37de3432a81913a7ca8f7f52"
        }
      ]
    }
  ]
}
