{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness3d-sdk",
    "version": "6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "liveness3d-sdk-6.9.aar",
          "url": "liveness3d-sdk-6.9.aar",
          "size": 2243576,
          "sha512": "ce80085cfc4880b01348acb7e325a4fe49a99e123bac96cce5c3f7fcecaaac1b493d9c40b9c6eccbb0537e3ed6c191eec55269d41d7b5d7532fa9fa558f76eb1",
          "sha256": "cd34c0a02ff764fe2c8c01ffab3094ee77988891e629290f72cca4f2794a82b6",
          "sha1": "adb16e8d41ba0a2f4e167c92eb000e58b4093fba",
          "md5": "a3f7bc3549d8510bf75059a2d898599a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.6.30"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "3.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "liveness3d-sdk-6.9.aar",
          "url": "liveness3d-sdk-6.9.aar",
          "size": 2243576,
          "sha512": "ce80085cfc4880b01348acb7e325a4fe49a99e123bac96cce5c3f7fcecaaac1b493d9c40b9c6eccbb0537e3ed6c191eec55269d41d7b5d7532fa9fa558f76eb1",
          "sha256": "cd34c0a02ff764fe2c8c01ffab3094ee77988891e629290f72cca4f2794a82b6",
          "sha1": "adb16e8d41ba0a2f4e167c92eb000e58b4093fba",
          "md5": "a3f7bc3549d8510bf75059a2d898599a"
        }
      ]
    }
  ]
}
