{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.6.2.aar",
          "url": "liveness2d-sdk-5.6.2.aar",
          "size": 2544782,
          "sha512": "a6bf1150d9b341d9100d96990a0e52cde2935edad0de91563aced3625531b43339e0ac6de869eb26d28614825680189d42669e8d13fa34c4d2d6bd03cba2ebb4",
          "sha256": "6169bd635b83e7ccb6359fe6a1d9854dea6ba889a4ae618be612f58f2c10b1a4",
          "sha1": "09a9d527f5b1f8ebe129e8fccd0fdfba53e89971",
          "md5": "984342ce92295afc9394e90aecfb42f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.6.2.aar",
          "url": "liveness2d-sdk-5.6.2.aar",
          "size": 2544782,
          "sha512": "a6bf1150d9b341d9100d96990a0e52cde2935edad0de91563aced3625531b43339e0ac6de869eb26d28614825680189d42669e8d13fa34c4d2d6bd03cba2ebb4",
          "sha256": "6169bd635b83e7ccb6359fe6a1d9854dea6ba889a4ae618be612f58f2c10b1a4",
          "sha1": "09a9d527f5b1f8ebe129e8fccd0fdfba53e89971",
          "md5": "984342ce92295afc9394e90aecfb42f5"
        }
      ]
    }
  ]
}
