{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "security",
    "version": "3.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "security-3.1.2.aar",
          "url": "security-3.1.2.aar",
          "size": 104451,
          "sha512": "2c7f66bfcbc2136ab9f56f79ad480b67c11ebb84e23a839df67db6b8c5cd4d062859f7d462a857f9582dd0ccdd2d009907f1b2efc57f127bb1935777a3b7ee6d",
          "sha256": "02b9f02d630598b74ddcc22aab52f218e9d1187b16ff21bd9d23ad18098bdaf8",
          "sha1": "97a95e1d0eb80773a14d03523c399b866c01bf47",
          "md5": "57cbc8c7c011a485adbfae276336becb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android-compat",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "security-3.1.2.aar",
          "url": "security-3.1.2.aar",
          "size": 104451,
          "sha512": "2c7f66bfcbc2136ab9f56f79ad480b67c11ebb84e23a839df67db6b8c5cd4d062859f7d462a857f9582dd0ccdd2d009907f1b2efc57f127bb1935777a3b7ee6d",
          "sha256": "02b9f02d630598b74ddcc22aab52f218e9d1187b16ff21bd9d23ad18098bdaf8",
          "sha1": "97a95e1d0eb80773a14d03523c399b866c01bf47",
          "md5": "57cbc8c7c011a485adbfae276336becb"
        }
      ]
    }
  ]
}
