{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness3d-sdk",
    "version": "6.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "liveness3d-sdk-6.7.1.aar",
          "url": "liveness3d-sdk-6.7.1.aar",
          "size": 2242903,
          "sha512": "e00264573fafcdbe6cefed6d4306ee34d70aa6a4917f85be85d6e061e78ca560d3e1ac0b6c7c59de5af5cf64da59678db7c459d316ed95566f3f172d531d1b7a",
          "sha256": "442eaa70d2ad3100c89c9c32fbcd42b42bf6e48a9dc155d9ac7bce6f8c176dd4",
          "sha1": "89578a3732a0e02c94941496a98a68dca13c1231",
          "md5": "38a2da0c5087770795ca5356ccad8d17"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.6.25"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        },
        {
          "group": "br.com.oiti",
          "module": "network",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "conceal"
            },
            {
              "group": "*",
              "module": "bcprov-jdk15on"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "liveness3d-sdk-6.7.1.aar",
          "url": "liveness3d-sdk-6.7.1.aar",
          "size": 2242903,
          "sha512": "e00264573fafcdbe6cefed6d4306ee34d70aa6a4917f85be85d6e061e78ca560d3e1ac0b6c7c59de5af5cf64da59678db7c459d316ed95566f3f172d531d1b7a",
          "sha256": "442eaa70d2ad3100c89c9c32fbcd42b42bf6e48a9dc155d9ac7bce6f8c176dd4",
          "sha1": "89578a3732a0e02c94941496a98a68dca13c1231",
          "md5": "38a2da0c5087770795ca5356ccad8d17"
        }
      ]
    }
  ]
}
